### ISSUE TITLE
Instance does not wait for event loop to finish.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js-env-selenium#55]
The `jsEnvTestKit` `TimeoutTests` test do not pass.

**Comment by gzm0** [comment]
This is functionality the current `JSEnv` specification does expect from JS VMs but in general cannot be expected. In other occasions (n.b. PhantomJS) we have hacked around this by implementing some sort of "auto termination".

In practice this is fragile. So in the future `JSEnv` will not expect automatic termination. As a result, we can leave the browser running until closing is requested.

In the meantime we will not fix this, since it is not an issue for the main use case of the `SeleniumJSEnv` (running tests).
